runtime: custom
env: flexible

env_variables:
  ASPNETCORE_URLS: 'http://0.0.0.0:8080'
  DOTNET_RUNNING_IN_CONTAINER: 'true'
  ConnectionStrings__DefaultConnection: "Server=/cloudsql/hardwarestore-8071e:europe-southwest1:bbdd1-tfg;Database=bbdd1-tfg;Uid=usuario;Pwd=1234;"

beta_settings:
  cloud_sql_instances: hardwarestore-8071e:europe-southwest1:bbdd1-tfg

#entrypoint: dotnet HardwareStoreAPI.dll

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 5
  cpu_utilization:
    target_utilization: 0.6
