// <auto-generated />
using HardwareStoreAPI.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HardwareStoreAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250515155613_parche2")]
    partial class parche2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("HardwareStoreAPI.Modelo.CarritoCompra", b =>
                {
                    b.Property<int>("id_carrito")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id_carrito"));

                    b.Property<int>("cantidad")
                        .HasColumnType("int");

                    b.Property<int>("id_producto")
                        .HasColumnType("int");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.HasKey("id_carrito");

                    b.HasIndex("userId")
                        .IsUnique();

                    b.ToTable("CarritoCompras");
                });

            modelBuilder.Entity("HardwareStoreAPI.Modelo.ListaFavoritos", b =>
                {
                    b.Property<int>("id_favorito")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id_favorito"));

                    b.Property<int>("id_producto")
                        .HasColumnType("int");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.HasKey("id_favorito");

                    b.HasIndex("userId")
                        .IsUnique();

                    b.ToTable("ListaFavoritos");
                });

            modelBuilder.Entity("HardwareStoreAPI.Modelo.Portatil", b =>
                {
                    b.Property<int>("IdProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdProducto"));

                    b.Property<int>("Bateria")
                        .HasColumnType("int");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ImagenUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NombreEmpresa")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NombreProducto")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("Pulgadas")
                        .HasColumnType("int");

                    b.Property<string>("Resolucion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("tipoPc")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdProducto");

                    b.ToTable("Portatiles");
                });

            modelBuilder.Entity("HardwareStoreAPI.Modelo.Sobremesa", b =>
                {
                    b.Property<int>("IdProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdProducto"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ImagenUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NombreEmpresa")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NombreProducto")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("tipoPc")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdProducto");

                    b.ToTable("Sobremesas");
                });

            modelBuilder.Entity("HardwareStoreAPI.Modelo.Usuario", b =>
                {
                    b.Property<int>("userId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("userId"));

                    b.Property<string>("UrlprofilePhoto")
                        .HasColumnType("longtext");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("userName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("userId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("HardwareStoreAPI.Modelo.CarritoCompra", b =>
                {
                    b.HasOne("HardwareStoreAPI.Modelo.Usuario", "Usuario")
                        .WithOne("CarritoCompra")
                        .HasForeignKey("HardwareStoreAPI.Modelo.CarritoCompra", "userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("HardwareStoreAPI.Modelo.ListaFavoritos", b =>
                {
                    b.HasOne("HardwareStoreAPI.Modelo.Usuario", "Usuario")
                        .WithOne("ListaFavoritos")
                        .HasForeignKey("HardwareStoreAPI.Modelo.ListaFavoritos", "userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("HardwareStoreAPI.Modelo.Usuario", b =>
                {
                    b.Navigation("CarritoCompra")
                        .IsRequired();

                    b.Navigation("ListaFavoritos")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
